resolver: lts-9.10

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
# - location:
#    git: https://github.com/commercialhaskell/stack.git
#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#   extra-dep: true
#  subdirs:
#  - auto-update
#  - wai
#
# A package marked 'extra-dep: true' will only be built if demanded by a
# non-dependency (i.e. a user package), and its test suites and benchmarks
# will not be run. This is useful for tweaking upstream packages.
packages:
- '.'
- location:
    git: https://github.com/supermario/elm-export-persistent.git
    commit: dea9e3af87bba51c0adf8c0e4b0da38f50dce4a8
  extra-dep: true

- location:
    git: https://github.com/supermario/hilt.git
    commit: 366cd9b59507240360df01986d48a8ba959537f1 # Current Master Sha
  extra-dep: true

# - location:
#     git: https://github.com/erlandsona/servant-generic.git
#     commit: f731610e499322fd49c40c1e82ecd36058fa0891
#   extra-dep: true
# - location:
#     git: https://github.com/erlandsona/servant-elm.git
#     commit: 4e27dcc8c135a3c2ced3f6d2de74133532dcd743
#   extra-dep: true
# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- heroku-0.1.2.3
- heroku-persistent-0.2.0
- servant-generic-0.1.0.0
- unagi-chan-0.4.0.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Not working on OSX
# See: https://github.com/commercialhaskell/stack/issues/2455
# &: https://github.com/docker/for-mac/issues/68
# docker:
#   enable: true
#   set-user: true
#   run-args: ["--ulimit=nofile=60000", "--memory=4g"]


# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.4"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
