branch-defaults:
  master:
    environment: Caldwell
environment-defaults:
  Caldwell:
    branch: null
    repository: null
global:
  application_name: caldwell
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Docker running on
    64bit Amazon Linux/2.8.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
