version: 2
jobs:
  api:
    docker:
      - image: fpco/stack-build:lts-9.10

    working_directory: /app
    steps:
      - checkout


      - restore_cache:
          key: deps

      - run:
          name: Build / Install Haskell executables
          command: stack --system-ghc --no-terminal install --local-bin-path .

      - save_cache:
         key: deps-{{checksum "package.yaml"}}-{{checksum "stack.yaml"}}
         paths:
          - "~/docker"
          - "~/.cabal"
          - "~/.local"
          - "~/.stack"
          - ".stack-work"

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install AWSCLI to push builds to Elastic Beanstalk.
          command: |
            sudo apt-get -qq update
            sudo apt-get -qq install python-pip libpython-dev
            sudo pip install -q awscli

            pip install awscli

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Build and Deploy docker image to Elastic Beanstalk
          command: ./bin/deploy $CIRCLE_SHA1

workflows:
  version: 2
  build-deploy:
    jobs:
      - api:
          filters:
            branches:
              only: master

test:
  override:
    - "test"
