#!/bin/bash

set -e

# Haskell Build and Generate Docs and Client Http Code.
stack build --system-ghc
stack exec elmify --system-ghc
stack exec docs --system-ghc

# Elm build
npm i
npm run build

# Run the Servant+Elm Application
stack exec caldwell --system-ghc
