#!/bin/bash

# This is what actually does the live stuff... it's basically just a little wrapper that does some 
# shell piping magic to fork two sub-shells, one that runs `make live-backend` and one for `make live-frontend`

function normal  { tput sgr0;    }
function red     { tput setaf 1; }
function green   { tput setaf 2; }
function yellow  { tput setaf 3; }
function blue    { tput setaf 4; }
function magenta { tput setaf 5; }
function cyan    { tput setaf 6; }
function white   { tput setaf 7; }

# Create two subprocesses to live run both frontend and backend, along with
# a colored prefix to keep the logs readable
make live-frontend 2>&1 | sed "s/^/$(magenta)[frontend]$(normal) /" & PIDFE=$!
make live-backend  2>&1 |    sed "s/^/$(blue) [backend]$(normal) /" & PIDBE=$!

# Wait on our subprocesses to finish before quitting
wait $PIDFE
wait $PIDBE
